#!/bin/bash
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf nb -kfold -execs 1 10 -dataset 11 -balance 0 -path TKFOLD/ -fileID TKFOLD -train_type 1 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf nb -kfold -execs 1 10 -dataset 11 -balance 1 -path TKFOLDb/ -fileID TKFOLDb -train_type 0 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf svm -param2 rbf -kfold -execs 1 10 -dataset 11 -balance 0 -path TKFOLD/ -fileID TKFOLD -train_type 1 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf svm -param2 rbf -kfold -execs 1 10 -dataset 11 -balance 1 -path TKFOLDb/ -fileID TKFOLDb -train_type 0 -optmize 1 1 auc &
htop
~
