#!/bin/bash
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf nb -execs 1 10 -dataset 20 -balance 0 -path TPCA/ -fileID TPCA -train_type 1 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf nb -execs 1 10 -dataset 20 -balance 1 -path TPCAb/ -fileID TPCAb -train_type 0 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf svm -param2 rbf -execs 1 10 -dataset 20 -balance 0 -path TPCA/ -fileID TPCA -train_type 1 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf svm -param2 rbf -execs 1 10 -dataset 20 -balance 1 -path TPCAb/ -fileID TPCAb -train_type 0 -optmize 1 1 auc &
htop
~
