#!/bin/bash
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf nb -execs 1 10 -dataset 10 -balance 0 -path T10_00/ -fileID T10_00 -train_type 1 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf nb -execs 1 10 -dataset 10 -balance 1 -path T10_00b/ -fileID T10_00b -train_type 0 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf nb -execs 1 10 -dataset 11 -balance 0 -path T10_01/ -fileID T10_01 -train_type 1 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf nb -execs 1 10 -dataset 11 -balance 1 -path T10_01b/ -fileID T10_01b -train_type 0 -optmize 1 1 auc &
htop
~
