#!/bin/bash
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf mlp -param 15 -param2 relu -execs 6 8 -dataset 14 -balance 0 -path TStp/ -fileID TStp -train_type 1 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf mlp -param 15 -param2 relu -execs 9 10 -dataset 14 -balance 0 -path TStp/ -fileID TStp -train_type 1 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf mlp -param 15 -param2 relu -execs 6 8 -dataset 14 -balance 1 -path TStpb/ -fileID TStpb -train_type 0 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf mlp -param 15 -param2 relu -execs 9 10 -dataset 14 -balance 1 -path TStpb/ -fileID TStpb -train_type 0 -optmize 1 1 auc &
htop
