#!/bin/bash
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf nb -execs 1 10 -dataset 4 -balance 0 -path T10_men/ -fileID T10_men -train_type 1 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf nb -execs 1 10 -dataset 4 -balance 1 -path T10_menb/ -fileID T10_menb -train_type 0 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf nb -execs 1 10 -dataset 5 -balance 0 -path T10_wom/ -fileID T10_wom -train_type 1 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf nb -execs 1 10 -dataset 5 -balance 1 -path T10_womb/ -fileID T10_womb -train_type 0 -optmize 1 1 auc &
htop
~
