#!/bin/bash
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -clf mlp -param 100 -param2 relu -execs 1 5 -dataset 2 -balance 0 -path T2/ -fileID T2 -optmize 2 1 TP 2 f1_S &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -clf mlp -param 100 -param2 relu -execs 6 10 -dataset 2 -balance 0 -path T2/ -fileID T2 -optmize 2 1 TP 2 f1_S &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -clf mlp -param 100 -param2 relu -execs 1 5 -dataset 2 -balance 1 -path T2b/ -fileID T2b -optmize 2 1 TP 2 f1_S &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -clf mlp -param 100 -param2 relu -execs 6 10 -dataset 2 -balance 1 -path T2b/ -fileID T2b -optmize 2 1 TP 2 f1_S &
htop
