#!/bin/bash
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -clf svm -execs 1 5 -dataset 2 -balance 0 -path T40/ -fileID T40 -train_type 1 -optmize 2 1 TP 2 f1_S &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -clf svm -execs 6 10 -dataset 2 -balance 0 -path T40/ -fileID T40 -train_type 1 -optmize 2 1 TP 2 f1_S &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -clf svm -execs 1 5 -dataset 2 -balance 1 -path T40b/ -fileID T40b -train_type 0 -optmize 2 1 TP 2 f1_S &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -clf svm -execs 6 10 -dataset 2 -balance 1 -path T40b/ -fileID T40b -train_type 0 -optmize 2 1 TP 2 f1_S &
htop
