#!/bin/bash
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf nb -execs 1 10 -dataset 17 -balance 0 -path TKC/ -fileID TKC -train_type 1 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf nb -execs 1 10 -dataset 17 -balance 1 -path TKCb/ -fileID TKCb -train_type 0 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf svm -param2 rbf -execs 1 10 -dataset 17 -balance 0 -path TKC/ -fileID TKC -train_type 1 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf svm -param2 rbf -execs 1 10 -dataset 17 -balance 1 -path TKCb/ -fileID TKCb -train_type 0 -optmize 1 1 auc &
htop
~
