#!/bin/bash
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf svm -param2 rbf -execs 6 8 -dataset 13 -balance 0 -path TNormStp/ -fileID TNormStp -train_type 1 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf svm -param2 rbf -execs 9 10 -dataset 13 -balance 0 -path TNormStp/ -fileID TNormStp -train_type 1 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf svm -param2 rbf -execs 1 5 -dataset 13 -balance 1 -path TNormStpb/ -fileID TNormStpb -train_type 0 -optmize 1 1 auc &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 10 -clf svm -param2 rbf -execs 6 10 -dataset 13 -balance 1 -path TNormStpb/ -fileID TNormStpb -train_type 0 -optmize 1 1 auc &
htop
