#!/bin/bash
nohup python3 main.py -v 0 -gen 500 -pop 100 -depth 40 -k 3 -execs 1 10 -dataset 2 -path Try_4/ -fileID ROC -optmize 2 1 TP 1 f1_S &
nohup python3 main.py -v 0 -gen 500 -pop 100 -depth 40 -k 5 -execs 1 10 -dataset 2 -path Try_4/ -fileID ROC -optmize 2 1 TP 1 f1_S &
nohup python3 main.py -v 0 -gen 500 -pop 100 -depth 40 -k 7 -execs 1 10 -dataset 2 -path Try_4/ -fileID ROC -optmize 2 1 TP 1 f1_S &
nohup python3 main.py -v 0 -gen 500 -pop 100 -depth 40 -k 9 -execs 1 10 -dataset 2 -path Try_4/ -fileID ROC -optmize 2 1 TP 1 f1_S &
htop
