#!/bin/bash
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -k 3 -execs 1 10 -dataset 7 -path Try_Vis2_B/ -fileID Vis2 -optmize 4 20 TP -5 FP -3 FN 1 TN &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -k 5 -execs 1 10 -dataset 7 -path Try_Vis2_B/ -fileID Vis2 -optmize 4 20 TP -5 FP -3 FN 1 TN &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -k 7 -execs 1 10 -dataset 7 -path Try_Vis2_B/ -fileID Vis2 -optmize 4 20 TP -5 FP -3 FN 1 TN &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -k 9 -execs 1 10 -dataset 7 -path Try_Vis2_B/ -fileID Vis2 -optmize 4 20 TP -5 FP -3 FN 1 TN &
htop
