#!/bin/bash
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -k 3 -execs 1 10 -dataset 7 -path Try_Vis2_A/ -fileID Vis2 -optmize 2 1 TP 2 f1_S &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -k 5 -execs 1 10 -dataset 7 -path Try_Vis2_A/ -fileID Vis2 -optmize 2 1 TP 2 f1_S &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -k 7 -execs 1 10 -dataset 7 -path Try_Vis2_A/ -fileID Vis2 -optmize 2 1 TP 2 f1_S &
htop
~
nohup python3 main.py -v 0 -gen 300 -pop 100 -depth 40 -k 9 -execs 1 10 -dataset 7 -path Try_Vis2_A/ -fileID Vis2 -optmize 2 1 TP 2 f1_S &
htop
